<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div id="multisite_manager_wrap">
    <table id="site_list">
        <thead>
            <tr>
                <th>Site ID</th>
                <th>Site URL</th>
                <th>Site Ajax URL</th>
                <th width="65%"><?php echo __('Site', 'aam'); ?></th>
                <th><?php echo __('Action', 'aam'); ?></th>
                <th>Default</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
    <div id="tap_default_site" class="aam-dialog" title="<?php echo __('Set Default Site', 'aam'); ?>">
        <p class="dialog-content">
            <?php echo __('Would you like to set the site', 'aam'); ?> <b><span id="default_site"></span></b> <?php echo __('as default?', 'aam'); ?>
        </p>
        <p class="dialog-note">
            <?php echo __('All newly created sites will inherit list of Roles & Capabilities.', 'aam'); ?>
        </p>
    </div>
</div>