<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div class="feature-content-container" id="my_feature_content">
    <div class="my-feature-banner">
       <p class="banner-style">
           <?php echo __('Do you need a custom feature? Ask us and we will develop it for you.', 'aam'); ?>
       </p> 
    </div>
    <div class="my-feature-actions">
        <a href="#" class="my-feature-action my-feature-message-action">
            <span><?php echo __('Email Us', 'aam'); ?></span>
        </a>
        <a href="http://wpaam.com/forum/viewtopic.php?f=7&t=72" target="_blank" class="my-feature-action my-feature-forum-action">
            <span><?php echo __('Ask on Forum', 'aam'); ?></span>
        </a>
    </div>
</div>