<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div id="visitor_manager_wrap" class="control-manager-visitor">
    <?php echo __('Control Access to your blog for visitor (any user that is not logged in)', 'aam'); ?>.
</div>